import http from "node:http";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const ROOT=path.dirname(fileURLToPath(import.meta.url)),PUBLIC=path.join(ROOT,"public");
const PORT=Number(process.env.PORT??8080),ODsayKey=process.env.ODSAY_API_KEY?.trim(),KakaoKey=process.env.KAKAO_JAVASCRIPT_KEY?.trim(),BusanBusKey=process.env.BUSAN_BUS_API_KEY?.trim();
const DEFAULT={sx:129.0594,sy:35.1577,ex:129.0086,ey:35.2105};
const CSV=[["부산광역시_무더위 쉼터_전처리.csv","무더위쉼터"],["부산광역시_한파쉼터_전처리.csv","한파쉼터"]];
const FACILITY_CSV=[["부산광역시_스마트_버스쉘터_설치_현황.csv","스마트 버스쉘터"],["부산전동휠체어급속충전기표준데이터.csv","전동휠체어 급속충전기"],["부산_AED_위경도_결과.csv","AED"]];
if(!ODsayKey||!KakaoKey||!BusanBusKey){console.error("Required API key is missing in .env");process.exit(1)}
const arr=v=>Array.isArray(v)?v:v?[v]:[];let routeCache,shelterCache,facilityCache;const walkCache=new Map(),busCache=new Map(),arrivalCache=new Map(),subwayTimetableCache=new Map();
const ARRIVAL_CACHE_MS=30000,BUSAN_ARRIVAL_URL="https://apis.data.go.kr/6260000/BusanBIMS/stopArrByBstopid";
const SUBWAY_TIMETABLE_CACHE_MS=21600000;
function csvRows(text){const out=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===","){row.push(field);field=""}else if(c==="\n"){row.push(field.replace(/\r$/,""));out.push(row);row=[];field=""}else field+=c}if(field||row.length){row.push(field.replace(/\r$/,""));out.push(row)}return out}
async function shelters(){if(shelterCache)return shelterCache;const all=[];for(const [file,type] of CSV){const text=new TextDecoder("euc-kr").decode(await readFile(path.join(ROOT,"data",file))).replace(/^\uFEFF/,""),rows=csvRows(text),heads=rows[0]??[];rows.slice(1).forEach((values,i)=>{if(values.length===1&&!values[0])return;const raw=Object.fromEntries(heads.map((h,n)=>[h,values[n]??""])),longitude=Number(raw["경도"]),latitude=Number(raw["위도"]);if(Number.isFinite(longitude)&&Number.isFinite(latitude))all.push({shelterType:type,sourceFile:file,dataIndex:i+1,csvRowNumber:i+2,sourceId:raw["연번"]||null,name:raw["쉼터명"]||"",address:raw["상세주소"]||raw["주소"]||"",longitude,latitude,sourceAttributes:raw})})}shelterCache=all;return all}
async function facilities(){if(facilityCache)return facilityCache;const all=[];for(const [file,type] of FACILITY_CSV){const encoding=type==="AED"?"utf-8":"euc-kr",text=new TextDecoder(encoding).decode(await readFile(path.join(ROOT,"data",file))).replace(/^\uFEFF/,""),rows=csvRows(text),heads=rows[0]??[];rows.slice(1).forEach((values,i)=>{if(values.length===1&&!values[0])return;const raw=Object.fromEntries(heads.map((h,n)=>[h,values[n]??""])),longitude=raw["경도"].trim()===""?NaN:Number(raw["경도"]),latitude=raw["위도"].trim()===""?NaN:Number(raw["위도"]);if(!Number.isFinite(longitude)||!Number.isFinite(latitude))return;if(type==="스마트 버스쉘터")all.push({facilityType:type,sourceFile:file,dataIndex:i+1,csvRowNumber:i+2,sourceId:raw["연번"]||null,sourceKey:null,name:raw["정류소명"]||"",address:raw["위치"]||"",longitude,latitude,sourceAttributes:raw});else if(type==="전동휠체어 급속충전기"){const name=raw["시설명"]||"",address=raw["소재지도로명주소"]||raw["소재지지번주소"]||"",sourceKey=[name,address,raw["설치장소설명"]||""].join("|");all.push({facilityType:type,sourceFile:file,dataIndex:i+1,csvRowNumber:i+2,sourceId:null,sourceKey,name,address,longitude,latitude,sourceAttributes:raw})}else all.push({facilityType:type,sourceFile:file,dataIndex:i+1,csvRowNumber:i+2,sourceId:raw["NO"]||null,sourceKey:null,name:raw["설치위치"]||"",address:raw["도로명주소"]||raw["지번주소"]||"",longitude,latitude,sourceAttributes:raw})})}facilityCache=all;return all}
async function odsay(endpoint,params){const q=new URLSearchParams({...params,output:"json",apiKey:ODsayKey}),res=await fetch(`https://api.odsay.com/v1/api/${endpoint}?${q}`),body=await res.json();if(!res.ok||body.error)throw new Error(body.error?.msg??body.error?.message??body.result?.message??body.result?.msg??body.message??JSON.stringify(body));return body}
const xmlDecode=value=>(value??"").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,"&").trim();
function xmlValue(xml,tag){const match=xml.match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`,"i"));return match?xmlDecode(match[1]):""}
const finiteOrNull=value=>{if(value===null||value===undefined||String(value).trim()==="")return null;const n=Number(value);return Number.isFinite(n)&&n>=0?n:null};
function parseBusanArrivalXml(xml){const code=xmlValue(xml,"resultCode"),message=xmlValue(xml,"resultMsg");if(code&&code!=="00")throw new Error(`부산버스 API ${code}: ${message||"요청 실패"}`);return[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(match=>{const item=match[1];return{arsno:xmlValue(item,"arsno"),bstopid:xmlValue(item,"bstopid"),stopName:xmlValue(item,"nodenm"),lineNo:xmlValue(item,"lineno"),lineId:xmlValue(item,"lineid"),busType:xmlValue(item,"bustype"),arrivals:[1,2].map(order=>{const minutes=finiteOrNull(xmlValue(item,`min${order}`)),stopsAway=finiteOrNull(xmlValue(item,`station${order}`)),lowCode=xmlValue(item,`lowplate${order}`);return{order,minutes,stopsAway,vehicleNo:xmlValue(item,`carno${order}`)||null,lowFloor:lowCode==="1"?true:lowCode==="0"?false:null,lowFloorCode:lowCode||null}}).filter(x=>x.minutes!==null||x.stopsAway!==null)}})}
async function busanStopArrivals(bstopid,force=false){const cached=arrivalCache.get(bstopid);if(!force&&cached&&Date.now()-cached.at<ARRIVAL_CACHE_MS)return{...cached,cacheHit:true};const q=new URLSearchParams({serviceKey:BusanBusKey,bstopid}),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const res=await fetch(`${BUSAN_ARRIVAL_URL}?${q}`,{signal:controller.signal}),text=await res.text();if(!res.ok)throw new Error(`부산버스 API HTTP ${res.status}`);const value={at:Date.now(),items:parseBusanArrivalXml(text),cacheHit:false};arrivalCache.set(bstopid,value);return value}catch(error){if(error.name==="AbortError")throw new Error("부산버스 API 응답 시간 초과");throw error}finally{clearTimeout(timer)}}
const routeText=value=>String(value??"").replace(/\s+/g,"").replace(/번$/g,"").toLowerCase();
function matchArrival(items,lane){return items.find(x=>lane.busLocalBlID&&String(x.lineId)===String(lane.busLocalBlID))??items.find(x=>routeText(x.lineNo)===routeText(lane.busNo))??null}
async function subwayTimetable(stationID,wayCode,force=false){const key=`${stationID}:${wayCode}`,cached=subwayTimetableCache.get(key);if(!force&&cached&&Date.now()-cached.at<SUBWAY_TIMETABLE_CACHE_MS)return{...cached,cacheHit:true};const body=await odsay("searchSubwaySchedule",{stationID,wayCode,showExpressTime:1,sepExpressTime:1}),value={at:Date.now(),result:body.result??{},cacheHit:false};subwayTimetableCache.set(key,value);return value}
const subwayDayList=(result,day)=>day===6?result.saturdaySchedule:day===0?result.holidaySchedule:result.weekdaySchedule;
function parseSubwayRows(rows,dayOffset=0){const trains=[];for(const row of arr(rows)){const match=String(row.departureTime??"").match(/^(\d{1,2}):(\d{2})$/);if(!match)continue;const hour=Number(match[1]),minute=Number(match[2]);trains.push({serviceMinutes:dayOffset*1440+hour*60+minute,destination:row.endStationName??null,subwayClass:row.subwayClass??0,firstLastFlag:row.firstLastFlag??0})}return trains}
function nextSubwayTrains(result,wayCode,nowMs=Date.now()){const kst=new Date(nowMs+32400000),day=kst.getUTCDay(),nowMinutes=kst.getUTCHours()*60+kst.getUTCMinutes()+kst.getUTCSeconds()/60,direction=Number(wayCode)===1?"up":"down",todayRows=subwayDayList(result,day)?.[direction],candidates=parseSubwayRows(todayRows);if(nowMinutes<180){const previousDay=(day+6)%7,previousRows=subwayDayList(result,previousDay)?.[direction];candidates.push(...parseSubwayRows(previousRows,-1).filter(train=>train.serviceMinutes>=0))}return candidates.filter(train=>train.serviceMinutes>=nowMinutes).sort((a,b)=>a.serviceMinutes-b.serviceMinutes).slice(0,2).map(train=>{const departureMinutes=((train.serviceMinutes%1440)+1440)%1440,hour=Math.floor(departureMinutes/60),minute=departureMinutes%60,remaining=Math.max(0,Math.ceil(train.serviceMinutes-nowMinutes));return{departureTime:`${String(hour).padStart(2,"0")}:${String(minute).padStart(2,"0")}`,minutesRemaining:remaining,destination:train.destination,subwayClass:train.subwayClass,firstLastFlag:train.firstLastFlag}})}
function num(q,k,d){const v=q.get(k);if(v===null)return d;const n=Number(v);if(!Number.isFinite(n))throw new Error(`${k} must be numeric`);return n}
function coords(url){return{sx:num(url.searchParams,"sx",DEFAULT.sx),sy:num(url.searchParams,"sy",DEFAULT.sy),ex:num(url.searchParams,"ex",DEFAULT.ex),ey:num(url.searchParams,"ey",DEFAULT.ey)}}
function segs(p){return arr(p.subPath?.length?p.subPath:p.rps)}
function sumSeg(s,i){return{segmentIndex:i,trafficType:s.trafficType??null,distanceM:s.distance??null,durationMin:s.duration??s.sectionTime??null,startName:s.startName??null,endName:s.endName??null,lines:arr(s.lane).map(x=>x.name??x.busNo).filter(Boolean),hasWalkGeometry:arr(s.routes).some(r=>arr(r.xyInfos).length)}}
function sumPath(p,i){return{routeNumber:i+1,pathType:p.pathType??null,totalTimeMin:p.info?.totalTime??null,totalWalkM:p.info?.totalWalk??null,busTransitCount:p.info?.busTransitCount??null,subwayTransitCount:p.info?.subwayTransitCount??null,firstStartStation:p.info?.firstStartStation??null,lastEndStation:p.info?.lastEndStation??null,hasMapObj:Boolean(p.info?.mapObj),segments:segs(p).map(sumSeg)}}
async function rawRoutes(c){const key=JSON.stringify(c);if(routeCache?.key===key&&Date.now()-routeCache.at<600000)return routeCache;const body=await odsay("searchPubTransPathT",{SX:c.sx,SY:c.sy,EX:c.ex,EY:c.ey,OPT:0,SearchType:0,SearchPathType:0});routeCache={key,at:Date.now(),coords:c,paths:arr(body.result?.path)};return routeCache}
async function routeList(c){const r=await rawRoutes(c);return{origin:{longitude:c.sx,latitude:c.sy},destination:{longitude:c.ex,latitude:c.ey},routeCount:r.paths.length,routes:r.paths.map(sumPath)}}
async function realtimeArrivals(n,c,force=false){const r=await rawRoutes(c),pathItem=r.paths[n-1];if(!pathItem)throw new Error("Route number is out of range");const indexed=segs(pathItem).map((segment,segmentIndex)=>({segment,segmentIndex})),busParts=indexed.filter(x=>x.segment.trafficType===2),subwayParts=indexed.filter(x=>x.segment.trafficType===1),stopIds=[...new Set(busParts.map(x=>String(x.segment.startLocalStationID??"")).filter(Boolean))],results=new Map();await Promise.all(stopIds.map(async bstopid=>{try{results.set(bstopid,{ok:true,...await busanStopArrivals(bstopid,force)})}catch(error){results.set(bstopid,{ok:false,error:error.message,items:[],cacheHit:false,at:Date.now()})}}));const busSegments=busParts.map(({segment,segmentIndex})=>{const bstopid=String(segment.startLocalStationID??""),result=results.get(bstopid)??{ok:false,error:"부산 정류소 ID가 없습니다.",items:[],cacheHit:false,at:Date.now()},buses=arr(segment.lane).map(lane=>{const matched=matchArrival(result.items,lane);return{busNo:lane.busNo??lane.name??"",localRouteId:lane.busLocalBlID??null,matchedLineId:matched?.lineId??null,busType:matched?.busType??null,arrivals:matched?.arrivals??[],status:matched?(matched.arrivals.length?"ok":"no_arrival"):"route_not_found"}});return{segmentIndex,stopName:segment.startName??"",bstopid:bstopid||null,arsId:segment.startArsID??null,ok:result.ok,error:result.error??null,cacheHit:result.cacheHit,fetchedAt:new Date(result.at).toISOString(),buses}});const subwaySegments=await Promise.all(subwayParts.map(async({segment,segmentIndex})=>{const stationID=segment.startID,wayCode=Number(segment.wayCode);if(!stationID||![1,2].includes(wayCode))return{segmentIndex,ok:false,error:"ODsay 승차역 또는 진행 방향 정보가 없습니다.",stationName:segment.startName??""};try{const timetable=await subwayTimetable(stationID,wayCode,force),result=timetable.result,departures=nextSubwayTrains(result,wayCode),directionName=departures[0]?.destination??segment.way??null;return{segmentIndex,ok:true,stationID,stationName:segment.startName??result.stationName??"",lineName:arr(segment.lane)[0]?.name??result.laneName??"",way:segment.way??null,wayCode,directionName,departures,cacheHit:timetable.cacheHit,fetchedAt:new Date(timetable.at).toISOString(),source:"ODsay 신규 시간표"}}catch(error){return{segmentIndex,ok:false,error:error.message,stationID,stationName:segment.startName??"",wayCode}}}));return{routeNumber:n,fetchedAt:new Date().toISOString(),cacheSeconds:ARRIVAL_CACHE_MS/1000,busSegments,subwaySegments}}
function pt(x,y){x=Number(x);y=Number(y);return Number.isFinite(x)&&Number.isFinite(y)?{longitude:x,latitude:y}:null}
function edge(s,side){if(side==="start")return s.trafficType===1?(pt(s.startExitX,s.startExitY)??pt(s.startX,s.startY)):pt(s.startX,s.startY);return s.trafficType===1?(pt(s.endExitX,s.endExitY)??pt(s.endX,s.endY)):pt(s.endX,s.endY)}
function walkPairs(ss,c){return ss.flatMap((s,i)=>{if(s.trafficType!==3||Number(s.distance??0)<=0)return[];const prev=[...ss.slice(0,i)].reverse().find(x=>x.trafficType!==3),next=ss.slice(i+1).find(x=>x.trafficType!==3),start=prev?edge(prev,"end"):pt(c.sx,c.sy),end=next?edge(next,"start"):pt(c.ex,c.ey);return start&&end?[{segmentIndex:i,reportedDistanceM:s.distance??null,reportedDurationMin:s.sectionTime??s.duration??null,start,end}]:[]})}
async function walkLine(pair){const key=`${pair.start.longitude},${pair.start.latitude},${pair.end.longitude},${pair.end.latitude}`;if(walkCache.has(key))return{...walkCache.get(key),segmentIndex:pair.segmentIndex};try{const body=await odsay("searchWalkPathV2",{opt:"reco",loc:key}),recommend=arr(body.result?.path)[0]?.recommend,points=[];for(const route of arr(recommend?.routes)){for(const item of arr(route.coordinate)){const p=pt(item.x,item.y),last=points[points.length-1];if(p&&(!last||last.longitude!==p.longitude||last.latitude!==p.latitude))points.push(p)}}if(points.length<2)throw new Error("No walking coordinates");const value={distanceM:recommend?.summary?.distance??pair.reportedDistanceM,durationSec:recommend?.summary?.duration??null,durationMin:pair.reportedDurationMin,geometryQuality:"odsay_walk_path",points};walkCache.set(key,value);return{...value,segmentIndex:pair.segmentIndex}}catch(error){return{segmentIndex:pair.segmentIndex,distanceM:pair.reportedDistanceM,durationMin:pair.reportedDurationMin,durationSec:null,geometryQuality:"straight_line_fallback",walkError:error.message,points:[pair.start,pair.end]}}}
async function walks(ss,c){return Promise.all(walkPairs(ss,c).map(walkLine))}
function stops(ss){const map=new Map();for(const s of ss){if(s.trafficType===3)continue;const candidates=[...arr(s.passStopList?.stations),{stationID:s.startID,stationName:s.startName,x:s.startX,y:s.startY},{stationID:s.endID,stationName:s.endName,x:s.endX,y:s.endY}];for(const x of candidates){const p=pt(x.x,x.y);if(!p)continue;map.set(`${x.stationID??""}:${p.longitude}:${p.latitude}`,{stationId:x.stationID??null,name:x.stationName??"",trafficType:s.trafficType,...p})}}return[...map.values()]}
async function busInfo(lane,startID){const id=lane.busID;if(!id)return{name:lane.busNo??lane.name??"",busID:null,direction:null};let detail=busCache.get(id);if(!detail){detail=(await odsay("busLaneDetail",{busID:id})).result;busCache.set(id,detail)}const boarding=arr(detail.station).find(s=>String(s.stationID)===String(startID)),code=Number(boarding?.stationDirection??0),direction=code===1?detail.busEndPoint:code===2?detail.busStartPoint:detail.busEndPoint;return{name:lane.busNo??detail.busNo??"",busID:id,direction:direction??null,routeStart:detail.busStartPoint??null,routeEnd:detail.busEndPoint??null}}
async function itinerary(ss,walkingLines){const result=[];for(let i=0;i<ss.length;i++){const s=ss[i];if(s.trafficType===3){const walk=walkingLines.find(x=>x.segmentIndex===i);result.push({segmentIndex:i,mode:"walk",distanceM:walk?.distanceM??s.distance??null,durationSec:walk?.durationSec??null,durationMin:s.sectionTime??s.duration??null,geometryQuality:walk?.geometryQuality??(Number(s.distance??0)===0?"indoor_station":"unavailable")});continue}const laneOptions=s.trafficType===2?await Promise.all(arr(s.lane).map(l=>busInfo(l,s.startID))):arr(s.lane).map(l=>({name:l.name??l.busNo??"",id:l.subwayCode??null,direction:s.way??null}));result.push({segmentIndex:i,mode:s.trafficType===1?"subway":"bus",startName:s.startName??null,endName:s.endName??null,startID:s.startID??null,endID:s.endID??null,direction:s.way??null,distanceM:s.distance??null,durationMin:s.sectionTime??s.duration??null,stationCount:s.stationCount??null,startExitNo:s.startExitNo??null,startExitLongitude:Number(s.startExitX),startExitLatitude:Number(s.startExitY),endExitNo:s.endExitNo??null,endExitLongitude:Number(s.endExitX),endExitLatitude:Number(s.endExitY),laneOptions,passStops:arr(s.passStopList?.stations).map(x=>({stationID:x.stationID??null,name:x.stationName??"",longitude:Number(x.x),latitude:Number(x.y)}))})}return result}
async function geometry(n,c){const r=await rawRoutes(c),p=r.paths[n-1];if(!p)throw new Error("Route number is out of range");if(!p.info?.mapObj)throw new Error("Route has no mapObj");const body=await odsay("loadLane",{mapObject:`0:0@${p.info.mapObj}`});const transitLines=arr(body.result?.lane).flatMap((lane,li)=>arr(lane.section).map((section,si)=>({laneIndex:li,sectionIndex:si,trafficClass:lane.class??null,type:lane.type??null,points:arr(section.graphPos).map(x=>pt(x.x,x.y)).filter(Boolean)})).filter(x=>x.points.length>1));const ss=segs(p),walkingLines=await walks(ss,c),indoorTransferCount=ss.filter(s=>s.trafficType===3&&Number(s.distance??0)===0).length,detailedItinerary=await itinerary(ss,walkingLines);return{route:sumPath(p,n-1),transitLines,walkingLines,indoorTransferCount,itinerary:detailedItinerary,stops:stops(ss)}}
function json(res,status,body){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(body))}
async function staticFile(res,p){const file=p==="/"? "index.html":p.slice(1);if(!["index.html","app.js","styles.css"].includes(file))return false;const body=await readFile(path.join(PUBLIC,file)),type=file.endsWith(".html")?"text/html; charset=utf-8":file.endsWith(".js")?"text/javascript; charset=utf-8":"text/css; charset=utf-8";res.writeHead(200,{"Content-Type":type,"Cache-Control":"no-store"});res.end(body);return true}
if(process.argv.includes("--smoke-test")){try{const r=await routeList(DEFAULT);console.log(JSON.stringify({routeCount:r.routeCount,firstRoute:r.routes[0]},null,2))}catch(e){console.error(`ODsay smoke test failed: ${e.message}`);process.exitCode=1}}
else{http.createServer(async(req,res)=>{try{const url=new URL(req.url??"/",`http://${req.headers.host}`);if(req.method==="GET"&&url.pathname==="/api/health")json(res,200,{ok:true});else if(req.method==="GET"&&url.pathname==="/api/config")json(res,200,{kakaoJavaScriptKey:KakaoKey});else if(req.method==="GET"&&url.pathname==="/api/shelters"){const s=await shelters();json(res,200,{count:s.length,shelters:s})}else if(req.method==="GET"&&url.pathname==="/api/facilities"){const f=await facilities();json(res,200,{count:f.length,facilities:f})}else if(req.method==="GET"&&url.pathname==="/api/routes")json(res,200,await routeList(coords(url)));else if(req.method==="GET"&&/^\/api\/routes\/\d+\/geometry$/.test(url.pathname))json(res,200,await geometry(Number(url.pathname.split("/")[3]),coords(url)));else if(req.method==="GET"&&/^\/api\/routes\/\d+\/realtime$/.test(url.pathname))json(res,200,await realtimeArrivals(Number(url.pathname.split("/")[3]),coords(url),url.searchParams.get("refresh")==="1"));else if(!(await staticFile(res,url.pathname)))json(res,404,{error:"Not found"})}catch(e){json(res,502,{error:e.message})}}).listen(PORT,"127.0.0.1",()=>console.log(`ODsay shelter map: http://localhost:${PORT}`))}
