import http from "node:http";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const ROOT=path.dirname(fileURLToPath(import.meta.url)),PUBLIC=path.join(ROOT,"public");
const PORT=Number(process.env.PORT??8080),ODsayKey=process.env.ODSAY_API_KEY?.trim(),KakaoKey=process.env.KAKAO_JAVASCRIPT_KEY?.trim();
const DEFAULT={sx:129.0594,sy:35.1577,ex:129.0086,ey:35.2105};
const CSV=[["부산광역시_무더위 쉼터_전처리.csv","무더위쉼터"],["부산광역시_한파쉼터_전처리.csv","한파쉼터"]];
const FACILITY_CSV=[["부산광역시_스마트_버스쉘터_설치_현황.csv","스마트 버스쉘터"],["부산전동휠체어급속충전기표준데이터.csv","전동휠체어 급속충전기"],["부산_AED_위경도_결과.csv","AED"]];
if(!ODsayKey||!KakaoKey){console.error("Required API key is missing in .env");process.exit(1)}
const arr=v=>Array.isArray(v)?v:v?[v]:[];let routeCache,shelterCache,facilityCache;const walkCache=new Map(),busCache=new Map();
function csvRows(text){const out=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===","){row.push(field);field=""}else if(c==="\n"){row.push(field.replace(/\r$/,""));out.push(row);row=[];field=""}else field+=c}if(field||row.length){row.push(field.replace(/\r$/,""));out.push(row)}return out}
async function shelters(){if(shelterCache)return shelterCache;const all=[];for(const [file,type] of CSV){const text=new TextDecoder("euc-kr").decode(await readFile(path.join(ROOT,"data",file))).replace(/^\uFEFF/,""),rows=csvRows(text),heads=rows[0]??[];rows.slice(1).forEach((values,i)=>{if(values.length===1&&!values[0])return;const raw=Object.fromEntries(heads.map((h,n)=>[h,values[n]??""])),longitude=Number(raw["경도"]),latitude=Number(raw["위도"]);if(Number.isFinite(longitude)&&Number.isFinite(latitude))all.push({shelterType:type,sourceFile:file,dataIndex:i+1,csvRowNumber:i+2,sourceId:raw["연번"]||null,name:raw["쉼터명"]||"",address:raw["상세주소"]||raw["주소"]||"",longitude,latitude,sourceAttributes:raw})})}shelterCache=all;return all}
async function facilities(){if(facilityCache)return facilityCache;const all=[];for(const [file,type] of FACILITY_CSV){const encoding=type==="AED"?"utf-8":"euc-kr",text=new TextDecoder(encoding).decode(await readFile(path.join(ROOT,"data",file))).replace(/^\uFEFF/,""),rows=csvRows(text),heads=rows[0]??[];rows.slice(1).forEach((values,i)=>{if(values.length===1&&!values[0])return;const raw=Object.fromEntries(heads.map((h,n)=>[h,values[n]??""])),longitude=raw["경도"].trim()===""?NaN:Number(raw["경도"]),latitude=raw["위도"].trim()===""?NaN:Number(raw["위도"]);if(!Number.isFinite(longitude)||!Number.isFinite(latitude))return;if(type==="스마트 버스쉘터")all.push({facilityType:type,sourceFile:file,dataIndex:i+1,csvRowNumber:i+2,sourceId:raw["연번"]||null,sourceKey:null,name:raw["정류소명"]||"",address:raw["위치"]||"",longitude,latitude,sourceAttributes:raw});else if(type==="전동휠체어 급속충전기"){const name=raw["시설명"]||"",address=raw["소재지도로명주소"]||raw["소재지지번주소"]||"",sourceKey=[name,address,raw["설치장소설명"]||""].join("|");all.push({facilityType:type,sourceFile:file,dataIndex:i+1,csvRowNumber:i+2,sourceId:null,sourceKey,name,address,longitude,latitude,sourceAttributes:raw})}else all.push({facilityType:type,sourceFile:file,dataIndex:i+1,csvRowNumber:i+2,sourceId:raw["NO"]||null,sourceKey:null,name:raw["설치위치"]||"",address:raw["도로명주소"]||raw["지번주소"]||"",longitude,latitude,sourceAttributes:raw})})}facilityCache=all;return all}
async function odsay(endpoint,params){const q=new URLSearchParams({...params,output:"json",apiKey:ODsayKey}),res=await fetch(`https://api.odsay.com/v1/api/${endpoint}?${q}`),body=await res.json();if(!res.ok||body.error)throw new Error(body.error?.msg??body.error?.message??body.result?.message??body.result?.msg??body.message??JSON.stringify(body));return body}
function num(q,k,d){const v=q.get(k);if(v===null)return d;const n=Number(v);if(!Number.isFinite(n))throw new Error(`${k} must be numeric`);return n}
function coords(url){return{sx:num(url.searchParams,"sx",DEFAULT.sx),sy:num(url.searchParams,"sy",DEFAULT.sy),ex:num(url.searchParams,"ex",DEFAULT.ex),ey:num(url.searchParams,"ey",DEFAULT.ey)}}
function segs(p){return arr(p.subPath?.length?p.subPath:p.rps)}
function sumSeg(s,i){return{segmentIndex:i,trafficType:s.trafficType??null,distanceM:s.distance??null,durationMin:s.duration??s.sectionTime??null,startName:s.startName??null,endName:s.endName??null,lines:arr(s.lane).map(x=>x.name??x.busNo).filter(Boolean),hasWalkGeometry:arr(s.routes).some(r=>arr(r.xyInfos).length)}}
function sumPath(p,i){return{routeNumber:i+1,pathType:p.pathType??null,totalTimeMin:p.info?.totalTime??null,totalWalkM:p.info?.totalWalk??null,busTransitCount:p.info?.busTransitCount??null,subwayTransitCount:p.info?.subwayTransitCount??null,firstStartStation:p.info?.firstStartStation??null,lastEndStation:p.info?.lastEndStation??null,hasMapObj:Boolean(p.info?.mapObj),segments:segs(p).map(sumSeg)}}
async function rawRoutes(c){const key=JSON.stringify(c);if(routeCache?.key===key&&Date.now()-routeCache.at<600000)return routeCache;const body=await odsay("searchPubTransPathT",{SX:c.sx,SY:c.sy,EX:c.ex,EY:c.ey,OPT:0,SearchType:0,SearchPathType:0});routeCache={key,at:Date.now(),coords:c,paths:arr(body.result?.path)};return routeCache}
async function routeList(c){const r=await rawRoutes(c);return{origin:{longitude:c.sx,latitude:c.sy},destination:{longitude:c.ex,latitude:c.ey},routeCount:r.paths.length,routes:r.paths.map(sumPath)}}
function pt(x,y){x=Number(x);y=Number(y);return Number.isFinite(x)&&Number.isFinite(y)?{longitude:x,latitude:y}:null}
function edge(s,side){if(side==="start")return s.trafficType===1?(pt(s.startExitX,s.startExitY)??pt(s.startX,s.startY)):pt(s.startX,s.startY);return s.trafficType===1?(pt(s.endExitX,s.endExitY)??pt(s.endX,s.endY)):pt(s.endX,s.endY)}
function walkPairs(ss,c){return ss.flatMap((s,i)=>{if(s.trafficType!==3||Number(s.distance??0)<=0)return[];const prev=[...ss.slice(0,i)].reverse().find(x=>x.trafficType!==3),next=ss.slice(i+1).find(x=>x.trafficType!==3),start=prev?edge(prev,"end"):pt(c.sx,c.sy),end=next?edge(next,"start"):pt(c.ex,c.ey);return start&&end?[{segmentIndex:i,reportedDistanceM:s.distance??null,reportedDurationMin:s.sectionTime??s.duration??null,start,end}]:[]})}
async function walkLine(pair){const key=`${pair.start.longitude},${pair.start.latitude},${pair.end.longitude},${pair.end.latitude}`;if(walkCache.has(key))return{...walkCache.get(key),segmentIndex:pair.segmentIndex};try{const body=await odsay("searchWalkPathV2",{opt:"reco",loc:key}),recommend=arr(body.result?.path)[0]?.recommend,points=[];for(const route of arr(recommend?.routes)){for(const item of arr(route.coordinate)){const p=pt(item.x,item.y),last=points[points.length-1];if(p&&(!last||last.longitude!==p.longitude||last.latitude!==p.latitude))points.push(p)}}if(points.length<2)throw new Error("No walking coordinates");const value={distanceM:recommend?.summary?.distance??pair.reportedDistanceM,durationSec:recommend?.summary?.duration??null,durationMin:pair.reportedDurationMin,geometryQuality:"odsay_walk_path",points};walkCache.set(key,value);return{...value,segmentIndex:pair.segmentIndex}}catch(error){return{segmentIndex:pair.segmentIndex,distanceM:pair.reportedDistanceM,durationMin:pair.reportedDurationMin,durationSec:null,geometryQuality:"straight_line_fallback",walkError:error.message,points:[pair.start,pair.end]}}}
async function walks(ss,c){return Promise.all(walkPairs(ss,c).map(walkLine))}
function stops(ss){const map=new Map();for(const s of ss){if(s.trafficType===3)continue;const candidates=[...arr(s.passStopList?.stations),{stationID:s.startID,stationName:s.startName,x:s.startX,y:s.startY},{stationID:s.endID,stationName:s.endName,x:s.endX,y:s.endY}];for(const x of candidates){const p=pt(x.x,x.y);if(!p)continue;map.set(`${x.stationID??""}:${p.longitude}:${p.latitude}`,{stationId:x.stationID??null,name:x.stationName??"",trafficType:s.trafficType,...p})}}return[...map.values()]}
async function busInfo(lane,startID){const id=lane.busID;if(!id)return{name:lane.busNo??lane.name??"",busID:null,direction:null};let detail=busCache.get(id);if(!detail){detail=(await odsay("busLaneDetail",{busID:id})).result;busCache.set(id,detail)}const boarding=arr(detail.station).find(s=>String(s.stationID)===String(startID)),code=Number(boarding?.stationDirection??0),direction=code===1?detail.busEndPoint:code===2?detail.busStartPoint:detail.busEndPoint;return{name:lane.busNo??detail.busNo??"",busID:id,direction:direction??null,routeStart:detail.busStartPoint??null,routeEnd:detail.busEndPoint??null}}
async function itinerary(ss,walkingLines){const result=[];for(let i=0;i<ss.length;i++){const s=ss[i];if(s.trafficType===3){const walk=walkingLines.find(x=>x.segmentIndex===i);result.push({segmentIndex:i,mode:"walk",distanceM:walk?.distanceM??s.distance??null,durationSec:walk?.durationSec??null,durationMin:s.sectionTime??s.duration??null,geometryQuality:walk?.geometryQuality??(Number(s.distance??0)===0?"indoor_station":"unavailable")});continue}const laneOptions=s.trafficType===2?await Promise.all(arr(s.lane).map(l=>busInfo(l,s.startID))):arr(s.lane).map(l=>({name:l.name??l.busNo??"",id:l.subwayCode??null,direction:s.way??null}));result.push({segmentIndex:i,mode:s.trafficType===1?"subway":"bus",startName:s.startName??null,endName:s.endName??null,startID:s.startID??null,endID:s.endID??null,direction:s.way??null,distanceM:s.distance??null,durationMin:s.sectionTime??s.duration??null,stationCount:s.stationCount??null,startExitNo:s.startExitNo??null,startExitLongitude:Number(s.startExitX),startExitLatitude:Number(s.startExitY),endExitNo:s.endExitNo??null,endExitLongitude:Number(s.endExitX),endExitLatitude:Number(s.endExitY),laneOptions,passStops:arr(s.passStopList?.stations).map(x=>({stationID:x.stationID??null,name:x.stationName??"",longitude:Number(x.x),latitude:Number(x.y)}))})}return result}
async function geometry(n,c){const r=await rawRoutes(c),p=r.paths[n-1];if(!p)throw new Error("Route number is out of range");if(!p.info?.mapObj)throw new Error("Route has no mapObj");const body=await odsay("loadLane",{mapObject:`0:0@${p.info.mapObj}`});const transitLines=arr(body.result?.lane).flatMap((lane,li)=>arr(lane.section).map((section,si)=>({laneIndex:li,sectionIndex:si,trafficClass:lane.class??null,type:lane.type??null,points:arr(section.graphPos).map(x=>pt(x.x,x.y)).filter(Boolean)})).filter(x=>x.points.length>1));const ss=segs(p),walkingLines=await walks(ss,c),indoorTransferCount=ss.filter(s=>s.trafficType===3&&Number(s.distance??0)===0).length,detailedItinerary=await itinerary(ss,walkingLines);return{route:sumPath(p,n-1),transitLines,walkingLines,indoorTransferCount,itinerary:detailedItinerary,stops:stops(ss)}}
function json(res,status,body){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(body))}
async function staticFile(res,p){const file=p==="/"? "index.html":p.slice(1);if(!["index.html","app.js","styles.css"].includes(file))return false;const body=await readFile(path.join(PUBLIC,file)),type=file.endsWith(".html")?"text/html; charset=utf-8":file.endsWith(".js")?"text/javascript; charset=utf-8":"text/css; charset=utf-8";res.writeHead(200,{"Content-Type":type,"Cache-Control":"no-store"});res.end(body);return true}
if(process.argv.includes("--smoke-test")){try{const r=await routeList(DEFAULT);console.log(JSON.stringify({routeCount:r.routeCount,firstRoute:r.routes[0]},null,2))}catch(e){console.error(`ODsay smoke test failed: ${e.message}`);process.exitCode=1}}
else{http.createServer(async(req,res)=>{try{const url=new URL(req.url??"/",`http://${req.headers.host}`);if(req.method==="GET"&&url.pathname==="/api/health")json(res,200,{ok:true});else if(req.method==="GET"&&url.pathname==="/api/config")json(res,200,{kakaoJavaScriptKey:KakaoKey});else if(req.method==="GET"&&url.pathname==="/api/shelters"){const s=await shelters();json(res,200,{count:s.length,shelters:s})}else if(req.method==="GET"&&url.pathname==="/api/facilities"){const f=await facilities();json(res,200,{count:f.length,facilities:f})}else if(req.method==="GET"&&url.pathname==="/api/routes")json(res,200,await routeList(coords(url)));else if(req.method==="GET"&&/^\/api\/routes\/\d+\/geometry$/.test(url.pathname))json(res,200,await geometry(Number(url.pathname.split("/")[3]),coords(url)));else if(!(await staticFile(res,url.pathname)))json(res,404,{error:"Not found"})}catch(e){json(res,502,{error:e.message})}}).listen(PORT,"127.0.0.1",()=>console.log(`ODsay shelter map: http://localhost:${PORT}`))}
